language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --no-scripts
  - php artisan key:generate
  - touch database/testing.sqlite

script: vendor/bin/phpunit