language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - travis_retry composer self-update
  - npm install -g npm@'>=3.8'
  - travis_retry npm install
  - travis_retry composer install

script: vendor/bin/phpunit